package com.mycompany.pi;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class TelaAdicionarEndereco extends javax.swing.JFrame {

    Usuarios u;
    Profissional p;
    Client c;
    
    
    public TelaAdicionarEndereco() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(true);
        initComponents();
    }
    public TelaAdicionarEndereco(Profissional p, Usuarios u) {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(true);
        initComponents();
        
        this.u =u;
        this.p = p;
        this.u.setNivel("profissional");
    }
    public TelaAdicionarEndereco(Client c, Usuarios u) {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(true);
        initComponents();
        
        this.u = u;
        this.c = c;
        this.u.setNivel("cliente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            Image background = new ImageIcon(getClass().getResource("/AdicionarEnd.png"
                + "")).getImage();

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.drawImage(background, 0, 0, getWidth(), getHeight(), this);
        }
    };
    endereco = new javax.swing.JTextField();
    num = new javax.swing.JTextField();
    complemento = new javax.swing.JTextField();
    tipo = new javax.swing.JComboBox<>();
    uf = new javax.swing.JComboBox<>();
    CONTINUAR = new javax.swing.JButton() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
            g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(getBackground());
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30); // Raio de arredondamento
            super.paintComponent(g);
            g2.dispose();
        }

        @Override
        protected void paintBorder(java.awt.Graphics g) {
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
            g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(getForeground());
            g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30); // Mesmo raio aqui
            g2.dispose();
        }
    };
    ;

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    endereco.setBackground(new java.awt.Color(255, 255, 255));
    endereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

    num.setBackground(new java.awt.Color(255, 255, 255));
    num.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

    complemento.setBackground(new java.awt.Color(255, 255, 255));
    complemento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

    tipo.setBackground(new java.awt.Color(255, 255, 255));
    tipo.setForeground(new java.awt.Color(0, 0, 0));
    tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Alameda (Al.)", "Avenida (Av.)", "Área (Área)", "Caminho (Caminho)", "Chácara (Chác.)", "Colônia (Col.)", "Conjunto (Conj.)", "Distrito (Dist.)", "Esplanada (Espl.)", "Estação (Estaç.)", "Estrada (Est.)", "Favela (Fav.)", "Fazenda (Faz.)", "Fórum (Fórum)", "Galeria (Gal.)", "Jardim (Jd.)", "Ladeira (Lad.)", "Lago (Lago)", "Lagoa (Lagoa)", "Largo (Lgo.)", "Loteamento (Lot.)", "Morro (Morro)", "Núcleo (Núcleo)", "Parque (Parque)", "Passarela (Pass.)", "Passagem (Pass.)", "Pátio (Pátio)", "Praça (Pça.)", "Quadra (Qd.)", "Recanto (Rec.)", "Residencial (Resid.)", "Rodovia (Rod.)", "Rua (R.)", "Setor (Setor)", "Sítio (Sítio)", "Travessa (Trav.)", "Trecho (Trecho)", "Trevo (Trevo)", "Vale (Vale)", "Vereda (Vereda)", "Via (Via)", "Viaduto (Viad.)", "Viela (Viela)", "Vila (Vila)" }));
    tipo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

    uf.setBackground(new java.awt.Color(255, 255, 255));
    uf.setForeground(new java.awt.Color(0, 0, 0));
    uf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Acre (AC)", "Amapá (AP)", "Amazonas (AM)", "Pará (PA)", "Rondônia (RO)", "Roraima (RR)", "Tocantins (TO)", "Alagoas (AL)", "Bahia (BA)", "Ceará (CE)", "Maranhão (MA)", "Paraíba (PB)", "Pernambuco (PE)", "Piauí (PI)", "Distrito Federal (DF)", "Goiás (GO)", "Mato Grosso (MT)", "Mato Grosso do Sul (MS)", "Rio Grande do Norte (RN)", "Sergipe (SE)", "Espírito Santo (ES)", "Minas Gerais (MG)", "Rio de Janeiro (RJ)", "São Paulo (SP)", "Paraná (PR)", "Rio Grande do Sul (RS)", "Santa Catarina (SC)", " " }));
    uf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

    CONTINUAR.setBackground(new java.awt.Color(138, 166, 163));
    CONTINUAR.setFont(new java.awt.Font("Forum", 1, 36)); // NOI18N
    CONTINUAR.setForeground(new java.awt.Color(255, 255, 255));
    CONTINUAR.setText("CONTINUAR");
    CONTINUAR.setBorderPainted(false);
    CONTINUAR.setContentAreaFilled(false);
    CONTINUAR.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            CONTINUARActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(83, 83, 83)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CONTINUAR, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(566, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(352, 352, 352)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(90, 90, 90)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
            .addComponent(CONTINUAR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(85, 85, 85))
    );

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CONTINUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONTINUARActionPerformed
        // TODO add your handling code here:
        if(num.getText().isBlank() || num.getText().isEmpty() ||
           endereco.getText().isBlank() || endereco.getText().isEmpty() ||
           tipo.getSelectedIndex() == 0 || uf.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Por favor, preenchar todos os campo!");
        }else{
            if(u.getNivel().equals("cliente")){
                
                AddressClient a = new AddressClient();
                
                a.setCompl(complemento.getText());
                a.setEndereco(endereco.getText());
                a.setNum(Integer.parseInt(num.getText()));
                a.setTipo(tipo.getSelectedItem().toString());
                a.setUf(uf.getSelectedItem().toString());
                

                
                DAOAdressClient.cadastrar(a);
                this.c.setIdAdress(a.getId());
                
                DAOClient.cadastrar(c);
                
                TelaPrincipal t = new TelaPrincipal(u, c);
                t.setVisible(true);
            }else{
               AddressProfissionals a = new AddressProfissionals();
                a.setCompl(complemento.getText());
                a.setEndereco(endereco.getText());
                a.setNum(Integer.parseInt(num.getText()));
                a.setTipo(tipo.getSelectedItem().toString());
                a.setUf(uf.getSelectedItem().toString());
                
                
                
                DAOAdressProfissionals.cadastrar(a);
                this.p.setIdAdress(a.getId());
                DAOProfissional.cadastrar(p);
                
                 TelaPrincipal t = new TelaPrincipal(u, p);
                 t.setVisible(true);
                
            }
            dispose();
        }
    }//GEN-LAST:event_CONTINUARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionarEndereco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CONTINUAR;
    private javax.swing.JTextField complemento;
    private javax.swing.JTextField endereco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField num;
    private javax.swing.JComboBox<String> tipo;
    private javax.swing.JComboBox<String> uf;
    // End of variables declaration//GEN-END:variables
}
