
package com.mycompany.pi;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class TelaEscolhaConta extends javax.swing.JFrame {

    public TelaEscolhaConta() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(true);
        
       //ClienteButton.setVisible(false);
       //ProfissionalButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel() {
            Image background = new ImageIcon(getClass().getResource("/EscolhaConta.png")).getImage();

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(background, 0, 0, getWidth(), getHeight(), this);
            }
        };
        ProfissionalButton = new javax.swing.JRadioButton();
        ClienteButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                    java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30); // Raio de arredondamento
                super.paintComponent(g);
                g2.dispose();
            }

            @Override
            protected void paintBorder(java.awt.Graphics g) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                    java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(getForeground());
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30); // Mesmo raio aqui
                g2.dispose();
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ProfissionalButton.setBackground(null);
        buttonGroup1.add(ProfissionalButton);
        ProfissionalButton.setFont(new java.awt.Font("Forum", 0, 36)); // NOI18N
        ProfissionalButton.setForeground(new java.awt.Color(0, 0, 0));
        ProfissionalButton.setText("PRESTO SERVIÇO");
        ProfissionalButton.setToolTipText("");
        ProfissionalButton.setFocusable(false);
        ProfissionalButton.setHideActionText(true);
        ProfissionalButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfissionalButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ProfissionalButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Collab-bro.png"))); // NOI18N
        ProfissionalButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Collab-bro - Copia.png"))); // NOI18N
        ProfissionalButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ProfissionalButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ProfissionalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfissionalButtonActionPerformed(evt);
            }
        });

        ClienteButton.setBackground(null);
        buttonGroup1.add(ClienteButton);
        ClienteButton.setFont(new java.awt.Font("Forum", 3, 36)); // NOI18N
        ClienteButton.setForeground(new java.awt.Color(0, 0, 0));
        ClienteButton.setText("SOU CLIENTE");
        ClienteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ClienteButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClienteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ClienteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Notebook-bro.png"))); // NOI18N
        ClienteButton.setIconTextGap(10);
        ClienteButton.setInheritsPopupMenu(true);
        ClienteButton.setName(""); // NOI18N
        ClienteButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Notebook-bro.png"))); // NOI18N
        ClienteButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Notebook-bro - Copia.png"))); // NOI18N
        ClienteButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ClienteButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(138, 166, 163));
        jButton1.setFont(new java.awt.Font("Forum", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CONTINUAR");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(ClienteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addGap(69, 69, 69)
                .addComponent(ProfissionalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addGap(146, 146, 146))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(522, 522, 522))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProfissionalButton)
                    .addComponent(ClienteButton))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProfissionalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfissionalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfissionalButtonActionPerformed

    private void ClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nivelU = null;
        
        if(ProfissionalButton.isSelected()){
            nivelU = "profissional";
        }else if(ClienteButton.isSelected()){
            nivelU = "cliente";
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, escolha um perfil");
        }
        
        if(nivelU!=null){
            TelaCriarConta t = new TelaCriarConta(nivelU);
            t.setVisible(true);
            this.dispose();
        }else{
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEscolhaConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ClienteButton;
    private javax.swing.JRadioButton ProfissionalButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
