package com.mycompany.pi;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class TelaAdicionarTel extends javax.swing.JFrame {

    String nivelU;
    Profissional p;
    Usuarios u;
    Client c;
    
    public TelaAdicionarTel() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(true);
        initComponents(); 
    }
    

     public TelaAdicionarTel(Profissional p, Usuarios u) {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(true);
        initComponents(); 
        
        this.u = u;
        nivelU = "profissional";
        this.p = p;
    }
     public TelaAdicionarTel(Client c, Usuarios u) {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(true);
        initComponents(); 
        
        this.u =u;
        nivelU = "cliente";
        this.c = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            Image background = new ImageIcon(getClass().getResource("/AdicionarTel.png"
                + "")).getImage();

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.drawImage(background, 0, 0, getWidth(), getHeight(), this);
        }
    };
    jTextField1 = new javax.swing.JTextField();
    jTextField2 = new javax.swing.JTextField();
    CONTINUAR = new javax.swing.JButton() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
            g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(getBackground());
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30); // Raio de arredondamento
            super.paintComponent(g);
            g2.dispose();
        }

        @Override
        protected void paintBorder(java.awt.Graphics g) {
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
            g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(getForeground());
            g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30); // Mesmo raio aqui
            g2.dispose();
        }
    };
    ;

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jTextField1.setBackground(new java.awt.Color(255, 255, 255));
    jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

    jTextField2.setBackground(new java.awt.Color(255, 255, 255));
    jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    jTextField2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField2ActionPerformed(evt);
        }
    });

    CONTINUAR.setBackground(new java.awt.Color(138, 166, 163));
    CONTINUAR.setFont(new java.awt.Font("Forum", 1, 36)); // NOI18N
    CONTINUAR.setForeground(new java.awt.Color(255, 255, 255));
    CONTINUAR.setText("CONTINUAR");
    CONTINUAR.setBorderPainted(false);
    CONTINUAR.setContentAreaFilled(false);
    CONTINUAR.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            CONTINUARActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(38, 38, 38)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 1459, Short.MAX_VALUE)
                .addComponent(jTextField1))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(1365, Short.MAX_VALUE)
            .addComponent(CONTINUAR, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(151, 151, 151))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(335, 335, 335)
            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(141, 141, 141)
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
            .addComponent(CONTINUAR, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(104, 104, 104))
    );

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void CONTINUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONTINUARActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().isBlank() || jTextField1.getText().isEmpty() ||
           jTextField2.getText().isBlank() || jTextField2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos!");
        }else{
            if(nivelU.equals("profissional")){
                PhoneProfissionals p = new PhoneProfissionals();
                CellphoneProfissional c = new CellphoneProfissional();
                
                p.setNum(jTextField2.getText());
                c.setNum(jTextField1.getText());

                DAOProfessionalCelphones.cadastrar(c);
                DAOProfissionalPhone.cadastrar(p);
                
                this.p.setIdCelphone(c.getId());
                this.p.setIdPhone(p.getId());
                
                TelaAdicionarEndereco t = new TelaAdicionarEndereco(this.p,this.u);
                
            }else{
                PhoneClients p = new PhoneClients();
                CelphoneClients c = new CelphoneClients();
                
                c.setNum(jTextField1.getText());
                p.setNum(jTextField2.getText());
                
                
                
                DAOClientCelphone.cadastrar(c);
                DAOClientPhone.cadastrar(p);
                
                this.c.setIdCelphone(c.getId());
                this.c.setIdPhone(p.getId());
                
                this.c.setIdCelphone(c.getId());
                this.c.setIdPhone(p.getId());
                TelaAdicionarEndereco t = new TelaAdicionarEndereco(this.c,this.u);
                t.setVisible(true);
            
            }
            dispose();
        }
        
    }//GEN-LAST:event_CONTINUARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarTel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarTel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarTel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarTel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionarTel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CONTINUAR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
