/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pi;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author loren
 */
public class VizualizarCliente extends javax.swing.JFrame {

    CellphoneProfissional cp;
    public VizualizarCliente() {
        initComponents();
    }
     public VizualizarCliente(Usuarios u, Profissional p) {
        initComponents();
        estrela1.setVisible(false);
        estrela2.setVisible(false);
        estrela3.setVisible(false);
        estrela4.setVisible(false);
        estrela5.setVisible(false);
        
        nome.setText(p.getNome());
        List<CellphoneProfissional> cells = DAOProfessionalCelphones.buscarPorId(p.getIdCelphone());
        if (!cells.isEmpty()) {
            CellphoneProfissional cell = cells.get(0);
            celular.setText("Celular:"+cell.getNum());
        } else {
            JOptionPane.showMessageDialog(null, "erro ao selecionar celular");
        }
        List<PhoneProfissionals> phons = DAOProfissionalPhone.buscarPorId(p.getIdPhone());
        if (!phons.isEmpty()) {
            PhoneProfissionals pon = phons.get(0);
            telefone.setText("Telefone:"+pon.getNum());
        } else {
            JOptionPane.showMessageDialog(null, "erro ao selecionar telefone");
        }
        List<Usuarios> users = UsuarioDAO.buscarPorId(p.getIdUser());
        if (!users.isEmpty()) {
            Usuarios user = users.get(0);
            email.setText("Email:"+user.getLogin());
        } else {
            JOptionPane.showMessageDialog(null, "erro ao selecionar email");
        }
        List<AddressProfissionals> adds = DAOAdressProfissionals.buscarPorId(p.getIdAdress());
        if (!adds.isEmpty()) {
            AddressProfissionals add = adds.get(0);
            endereco.setText("Endereço:"+add.getEndereco()+" "+add.getNum()+" "+add.getCompl());
            uf.setText("UF:"+add.getUf());
        } else {
            JOptionPane.showMessageDialog(null, "erro ao selecionar uf");
        }
        desc.setText(p.getDesc());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nome = new javax.swing.JLabel();
        estrela2 = new javax.swing.JLabel();
        estrela1 = new javax.swing.JLabel();
        estrela3 = new javax.swing.JLabel();
        estrela4 = new javax.swing.JLabel();
        estrela5 = new javax.swing.JLabel();
        celular = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        endereco = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        uf = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(221, 226, 226));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 111, 97), 3, true));
        jPanel1.setOpaque(false);

        nome.setFont(new java.awt.Font("Forum", 1, 24)); // NOI18N
        nome.setText("Nome");

        estrela2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        estrela2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star.png"))); // NOI18N

        estrela1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        estrela1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star.png"))); // NOI18N

        estrela3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        estrela3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star.png"))); // NOI18N

        estrela4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        estrela4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star.png"))); // NOI18N

        estrela5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        estrela5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star.png"))); // NOI18N

        celular.setFont(new java.awt.Font("Forum", 1, 24)); // NOI18N
        celular.setText("Celular:");

        telefone.setFont(new java.awt.Font("Forum", 1, 24)); // NOI18N
        telefone.setText("Telefone:");

        email.setFont(new java.awt.Font("Forum", 1, 24)); // NOI18N
        email.setText("Email:");

        endereco.setFont(new java.awt.Font("Forum", 1, 24)); // NOI18N
        endereco.setText("Endereço:");

        desc.setBackground(new java.awt.Color(204, 204, 204));
        desc.setFont(new java.awt.Font("Forum", 1, 12)); // NOI18N
        desc.setForeground(new java.awt.Color(0, 0, 0));
        desc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        desc.setText("Descrição:");
        desc.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        desc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        uf.setFont(new java.awt.Font("Forum", 1, 24)); // NOI18N
        uf.setText("UF:");

        jLabel13.setFont(new java.awt.Font("Forum", 1, 24)); // NOI18N
        jLabel13.setText("Descrição:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(estrela1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estrela2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estrela3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estrela4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estrela5))
                            .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estrela2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estrela1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estrela3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estrela4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estrela5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VizualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VizualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VizualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VizualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VizualizarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel celular;
    private javax.swing.JLabel desc;
    private javax.swing.JLabel email;
    private javax.swing.JLabel endereco;
    private javax.swing.JLabel estrela1;
    private javax.swing.JLabel estrela2;
    private javax.swing.JLabel estrela3;
    private javax.swing.JLabel estrela4;
    private javax.swing.JLabel estrela5;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel telefone;
    private javax.swing.JLabel uf;
    // End of variables declaration//GEN-END:variables
}
